[package]
name = "ken"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
codespan-reporting = "0.12.0"
kenc = { path = "../kenc" }
kenvm = { path = "../kenvm" }
kenspan = { path = "../kenspan" }
reedline = "0.40.0"

[lints]
workspace = true
